# Generated by Django 5.2.1 on 2025-05-09 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50)),
                ('insurance_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('company', models.CharField(choices=[('INSON', 'INSON'), ('UzInsurance', 'UzInsurance'), ('KapitalSugurta', 'Kapital Sugurta')], max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
